remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Aimc6594 Dev
description: Este script en Python está diseñado para analizar archivos HTML y CSS, y combinar los resultados para identificar y clasificar los elementos activos e inactivos en una página web.
logo: logo.png
show_downloads: false
